apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: express
  replicas: 1
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: quay.io/acidonpe/express-post
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: default
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
